export * from "./dummy.entity";
export * from "./user.entity";
export * from "./role.entity";
export * from "./sacrament.entity";
export * from "./region.entity";
export * from "./committee.entity";
export * from "./association.entity";
export * from "./responsability.entity";
export * from "./event.entity";
